use std::hash::Hash;

/// Necessary to protect the internal `usize`, which, in the absence of this wrapper,
/// would be public in the module calling [`register_blazemap_id_wrapper`](crate::register_blazemap_id_wrapper).
///
/// Publicity of the internal `usize` may lead to:
/// * UB if the programmer of the downstream crate would accidentally mutate it.
/// * Incorrect auto-derives of standard traits such as `Default`, `Debug`, `Display`,
///   `PartialOrd`, `Ord`, `serde::Serialize` and `serde::Deserialize`.
#[derive(Clone, Copy, Eq, PartialEq, Hash)]
#[repr(transparent)]
#[doc(hidden)]
pub struct PrivateIndex(usize);

impl PrivateIndex
{
    #[inline(always)]
    pub unsafe fn new(index: usize) -> Self {
        Self(index)
    }

    #[inline(always)]
    pub fn into_inner(self) -> usize {
        self.0
    }
}

#[cfg(test)]
mod tests
{
    use std::fmt::{Debug, Display};

    #[cfg(feature = "serde")]
    use serde::{Deserialize, Serialize};
    use static_assertions::assert_not_impl_any;

    use crate::utils::private_index::PrivateIndex;

    // These assertions are needed in order to prevent standard traits
    // from being automatically derived for types
    // generated by the [`register_blazemap_id_wrapper`](crate::register_blazemap_id) macro.
    assert_not_impl_any!(PrivateIndex: Default, Debug, Display, PartialOrd);

    #[cfg(feature = "serde")]
    assert_not_impl_any!(PrivateIndex: Serialize, Deserialize<'static>);
}